config/routes.rb
Rails.application.routes.draw do
  get 'home/about'
  root to:'home#top'
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :destroy ,:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show,:edit,:update,:index]
  get'books/:id'=>'books#show',as:'show_books'
patch'books/:id'=>'books#update',as:'apdate_books'
delete'books/:id' =>'books#destroy',as:'destroy_books'
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true ,length: { maximum: 200 }
end  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :books,dependent: :destroy
         attachment :profile_image
        
         validates :name, uniqueness: true, presence: true, length:{ minimum: 2 ,maximum: 20 }
         validates :introduction, length:{ maximum: 50 }
       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
 

protected

def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sing_up, keys:[:name])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:email])

end

def after_sign_in_path_for(resource)
   user_path(current_user.id)
end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
before_action :ensure_correct_user,only: [:update,:edit,:destroy]

 def show
      @book_new = Book.new
      @book = Book.find(params[:id])
      @user = @book.user
      @books = @user.books.page(params[:page]).reverse_order
  end

 def index
      @book = Book.new
      @users =  User.all
      @books = Book.all
      @user =  current_user

end

 def create
   @book = Book.new(book_params)
   @book.user_id = current_user.id
   @user = current_user


    if @book.save
      flash[:notice] = "You have created book successfully"
      redirect_to book_path(@book.id)

   else
    @books = Book.all
    render action: :index

    end
end

  def edit
     @book = Book.find(params[:id])


  end

  def update
    @book = Book.find(params[:id])


   if  @book.update(book_params)
    flash[:notice] = "You have created book successfully"
    redirect_to book_path(@book.id)

  else
    render action: :edit

  end
end

  def destroy
    @book = Book.find(params[:id])
    p @book
    @book.destroy

    redirect_to books_path
  end

  private

  def book_params
   params.require(:book).permit(:title, :body)
  end

def ensure_correct_user
    @book = Book.find(params[:id])
    if @book.user.id != current_user.id
      redirect_to "/books"
 end

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user,only: [:update,:edit]
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

  end

  def index
      @users = User.all
      @user = current_user
      @books = @user.books.page(params[:page]).reverse_order
      @book = Book.new
  end

  def edit
    @user = User.find(params[:id])

  end

  def update
   @user =User.find(params[:id])

 if
   @user.update(user_params)
   flash[:notice] = "You have update user successfully"
   redirect_to user_path(@user.id)

 else
    render action: :edit

  end

end

  def user_params
   params.require(:user).permit(:name, :profile_image, :introduction)
  end

def ensure_correct_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
 end
end

 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
<div class ="row">
<div class ="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>

<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this book from being saved:
<% @book.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>

<% end %>

<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <div class="form-group">
   <label for="book_title">Title</label></br>
   <%= f.text_field :title %>
  </div>
  <div class="fome-group">
    <label for="book_body">Body</label></br>
    <%= f.text_area :body %>
  </div>
  <div class="fome-group">
  <%= f.submit 'Update Book' , class:'btn btn-success' %>
  </div>
<% end %>

<%= link_to "Show",book_path(@book.id) %>
|
<%= link_to "Back", "/books"%>
  </div>
  </div>
</div>

app/views/books/index.html.erb
<% if flash[:notice] %>
 <p id="notice"><%= flash[:notice] %></p>
<% end %> 

<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this book from being saved:
<% @book.errors.full_messages.each do |message| %>

<li><%= message %></li>

<% end %>

<% end %>

<main>
<p id ="notice"></p>

<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
　<h2>User info</h2>

  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
      <th>name</th>
      <th><%= @user.name %></th>
      </tr>
      <tr>
       <th>
        introduction
       </th>
       <th>
        <%= @user.introduction %>
       </th>
      </tr>
     </tbody>
  </table>
       
  <div class ="row">
    <%= link_to "", edit_user_path(@user) ,class: 'btn btn-outline-secondary btn-block fas fa-user-cog'  %>
  </div>
  
<h2 class="mt-3">New book</h2>

<%= form_with model:@book, local:true do |f| %>

<div class="form-group">
  <label for="book_title">Title</label></br>
  <%= f.text_field :title %>
</div>

<div class="form-group">
  <label for="book_body">opinion</label></br>
  <%= f.text_area :body %>
</div>

<div class="form-group">
  <%= f.submit 'Create Book' ,class: 'btn btn-success'%>
</div>
<%end%>
</div>

<!--ここから右側-->

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
           <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
         <tr>
          <td><%= link_to (attachment_image_tag book.user,:profile_image, :fill, 40, 40, fallback: "no_image.jpg",size:'40x40', class:"attachment user profile_image fallback") ,user_path(book.user.id)%></td>
          <td><%= link_to book.title,book_path(book.id) %></td>
          <td><%=book.body %></td>
         </tr>
        </tbody>
        <% end %>
     </table>
</div></div>
</div>
</div>
</main>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
 <p id="notice"><%= flash[:notice] %></p>
<% end %>

<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this book from being saved:
<% @book.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>

<% end %>

<main>
<p id ="notice"></p>

<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
　<h2>User info</h2>

  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
      <th>name</th>
      <th><%= @user.name %></th>
      </tr>
      <tr>
       <th>
        introduction
       </th>
       <th>
        <%= @user.introduction %>
       </th>
      </tr>
     </tbody>
  </table>

  <div class ="row">
    <%= link_to "", edit_user_path(@user) ,class: 'btn btn-outline-secondary btn-block fas fa-user-cog'  %>
  </div>



<h2 class="mt-3">New book</h2>

<%= form_with model:@book_new, local:true do |f| %>

<div class="form-group">
  <label for="book_title">Title</label></br>
  <%= f.text_field :title %>
</div>

<div class="form-group">
  <label for="book_body">opinion</label></br>
  <%= f.text_area :body %>
</div>

<div class="form-group">
  <%= f.submit 'Create Book' ,class: 'btn btn-success'%>
</div>
<%end%>
</div>

<!--ここから右側-->

<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
      <table class="table table-hover table-inverse">

        <tbody>
         <tr>
          <td><%=attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",size:'40x40', class:"attachment user profile_image fallback"; %></br>
          <%= link_to @user.name ,user_path(@user.id) %></td>
          <td><%= link_to @book.title,book_path(@book.id) %></td>
          <td><%=@book.body %></td>
           <% if @user.id == current_user.id %>
          <td><%=link_to "Edit",edit_book_path(@book.id), class:'btn btn-sm btn-success'%></td>
          <td><%= link_to "Destroy", destroy_books_path(@book.id), method: :delete, "data-confirm" => "本当に削除してよろしいですか?" ,class:'btn btn-sm btn-danger'%></td>
          <td>
          <% end %>
         </tr>
        </tbody>

     </table>
</div></div>
</div>
</div>
</main>

app/views/home/about.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/home/top.html.erb
<% if flash[:notice] %>
 <p id="notice"><%= flash[:notice] %></p>
<% end %> 


<body>
      <main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>


      </main>
</body>

app/views/homes/top.html.erb
<body>

      <main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>


      </main>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<header>
  <body>
  <% if user_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li><%= link_to "Home",  user_path(current_user.id), class: 'fas fa-home nav-link text-light'%></li>
          <li><%= link_to "Users", "/users", class: 'fas fa-users nav-link text-light'%></li>
          <li><%= link_to "Books", "/books", class: 'fas fa-book-open nav-link text-light'%></li>
          <li><%= link_to "logout", destroy_user_session_path, method: :delete , class: 'fas fa-sign-out-alt nav-link text-light'%></li>
        </ul>
      </div>
    </div>
  </nav>


  <% else %>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
     <li class="nav-item">
        <%= link_to 'Home', '/'  , class: 'fas fa-home nav-link text-light' %>
      </li>
      <li class="nav-item">
        <%= link_to "About", "/home/about" ,class: 'fas fa-link nav-link text-light'%>
      </li>
      <li class="nav-item">
        <%= link_to "sign up", new_user_registration_path ,class: 'fas fa-user-plus nav-link text-light'%>
      </li>
      <li class="nav-item">
        <%= link_to "login", new_user_session_path , class: 'fas fa-sign-in-alt nav-link text-light'%>
      </li>
      <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>



    <%= yield %>

<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

  </body>
</html>

app/views/users/edit.html.erb
<% if flash[:notice] %>
 <p id="notice"><%= flash[:notice] %></p>
<% end %> 
<% if @user.errors.any? %>
<%= @user.errors.count %>errors prohibited this book from being saved:
<% @user.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>

<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <p id="notice"></p>
<div class="form-group">
<h2>User info</h2>
<%= form_with model:@user, local:true do |f| %>
<div>
<div class="form-group">
  <label for="inputName">Name</label></br>
  <%= f.text_field :name, autofocus: true, id:"inputName"%>
<div class="form-group"> 
  <label for="inputImage">Image</label></br>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
</div>
<div class="form-group">
  <label for="inputImage">introduction</label></br>
  <%= f.text_area :introduction %>
</div>
<div class="form-group">
  <%= f.submit "Update User" ,class:'btn btn-secondary'%>
</div>
<% end %>

app/views/users/index.html.erb
<% if flash[:notice] %>
 <p id="notice"><%= flash[:notice] %></p>
<% end %> 

<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this book from being saved:
<% @book.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>

<% end %>

<main>
<p id ="notice"></p>

<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
　<h2>User info</h2>

  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
      <th>name</th>
      <th><%= @user.name %></th>
      </tr>
      <tr>
       <th>
        introduction
       </th>
       <th>
        <%= @user.introduction %>
       </th>
      </tr>
     </tbody>
  </table>
       
  <div class ="row">
    <%= link_to "", edit_user_path(@user) ,class: 'btn btn-outline-secondary btn-block fas fa-user-cog'  %>
  </div>
  
<h2 class="mt-3">New book</h2>

<%= form_with model:@book, local:true do |f| %>

<div class="form-group">
  <label for="book_title">Title</label></br>
  <%= f.text_field :title %>
</div>

<div class="form-group">
  <label for="book_body">opinion</label></br>
  <%= f.text_area :body %>
</div>

<div class="form-group">
  <%= f.submit 'Create Book' ,class: 'btn btn-success'%>
</div>
<%end%>
</div>

<!--ここから右側-->

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
           <th>image</th>
           <th>name</th>
           <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
         <tr>
         <td> <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",size:'40x40', class:"attachment user profile_image fallback"; %></td>
         <td><%=user.name %></td>
         <td><%= link_to "Show",user_path(user.id) ,class:user_path(user.id)%></td>
         </tr>
        </tbody>
        <% end %>
     </table>
</div>
</div>
</div>
</main>

app/views/users/show.html.erb
<% if flash[:notice] %>
 <p id="notice"><%= flash[:notice] %></p>
<% end %>

<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this book from being saved:
<% @book.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>

<% end %>

<main>
<p id ="notice"></p>

<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
　<h2>User info</h2>

  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
      <th>name</th>
      <th><%= @user.name %></th>
      </tr>
      <tr>
       <th>
        introduction
       </th>
       <th>
        <%= @user.introduction %>
       </th>
      </tr>
     </tbody>
  </table>

  <div class ="row">
    <%= link_to "", edit_user_path(@user) ,class: 'btn btn-outline-secondary btn-block fas fa-user-cog'  %>
  </div>

<h2 class="mt-3">New book</h2>

<%= form_with model:@book, local:true do |f| %>

<div class="form-group">
  <label for="book_title">Title</label></br>
  <%= f.text_field :title %>
</div>

<div class="form-group">
  <label for="book_body">opinion</label></br>
  <%= f.text_area :body %>
</div>

<div class="form-group">
  <%= f.submit 'Create Book' ,class: 'btn btn-success'%>
</div>
<%end%>
</div>

<!--ここから右側-->

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
           <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
         <tr>
          <td><%= link_to (attachment_image_tag book.user,:profile_image, :fill, 40, 40, fallback: "no_image.jpg",size:'40x40', class:"attachment user profile_image fallback") ,user_path(book.user.id)%></td>
          <td><%= link_to book.title,book_path(book.id) %></td>
          <td><%=book.body %></td>
         </tr>
        </tbody>
        <% end %>
     </table>
</div></div>
</div>
</div>
</main>